/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 11:44:53 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.service.criteria;

/**
 * Criteria bean used for Addresses search.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public class AddressesCriteria {

    private String line1; 
    private String line2; 
    private String line3; 
    private String line4; 
    private String city; 
    private String zipPostcode; 
    private String stateProvinceCounty; 
    private String country; 
    private String otherAddressDetails; 
	// Constructor
	public AddressesCriteria() {
		// Needed empty constructor for serialization
	}

	public void setLine1(String line1) {this.line1 = line1;}
	public String getLine1() {return this.line1;}
	public void setLine2(String line2) {this.line2 = line2;}
	public String getLine2() {return this.line2;}
	public void setLine3(String line3) {this.line3 = line3;}
	public String getLine3() {return this.line3;}
	public void setLine4(String line4) {this.line4 = line4;}
	public String getLine4() {return this.line4;}
	public void setCity(String city) {this.city = city;}
	public String getCity() {return this.city;}
	public void setZipPostcode(String zipPostcode) {this.zipPostcode = zipPostcode;}
	public String getZipPostcode() {return this.zipPostcode;}
	public void setStateProvinceCounty(String stateProvinceCounty) {this.stateProvinceCounty = stateProvinceCounty;}
	public String getStateProvinceCounty() {return this.stateProvinceCounty;}
	public void setCountry(String country) {this.country = country;}
	public String getCountry() {return this.country;}
	public void setOtherAddressDetails(String otherAddressDetails) {this.otherAddressDetails = otherAddressDetails;}
	public String getOtherAddressDetails() {return this.otherAddressDetails;}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(line1); 
		sb.append("|"); 
		sb.append(line2); 
		sb.append("|"); 
		sb.append(line3); 
		sb.append("|"); 
		sb.append(line4); 
		sb.append("|"); 
		sb.append(city); 
		sb.append("|"); 
		sb.append(zipPostcode); 
		sb.append("|"); 
		sb.append(stateProvinceCounty); 
		sb.append("|"); 
		sb.append(country); 
		sb.append("|"); 
		sb.append(otherAddressDetails); 
        return sb.toString();
	}
}
