package com.ifi.entity;
// Generated Sep 27, 2018 11:38:39 AM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Accounts generated by hbm2java
 */
@Entity
@Table(name = "accounts", catalog = "student_loans")
public class Accounts implements java.io.Serializable {

	private Integer accountId;
	private RefAccountTypes refAccountTypes;
	private RefBanks refBanks;
	private Students students;
	private Integer accountNumber;
	private String otherAccountDetails;

	public Accounts() {
	}

	public Accounts(RefAccountTypes refAccountTypes, RefBanks refBanks, Students students, Integer accountNumber,
			String otherAccountDetails) {
		this.refAccountTypes = refAccountTypes;
		this.refBanks = refBanks;
		this.students = students;
		this.accountNumber = accountNumber;
		this.otherAccountDetails = otherAccountDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "account_id", unique = true, nullable = false)
	public Integer getAccountId() {
		return this.accountId;
	}

	public void setAccountId(Integer accountId) {
		this.accountId = accountId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_type_code")
	public RefAccountTypes getRefAccountTypes() {
		return this.refAccountTypes;
	}

	public void setRefAccountTypes(RefAccountTypes refAccountTypes) {
		this.refAccountTypes = refAccountTypes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bank_code")
	public RefBanks getRefBanks() {
		return this.refBanks;
	}

	public void setRefBanks(RefBanks refBanks) {
		this.refBanks = refBanks;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "student_id")
	public Students getStudents() {
		return this.students;
	}

	public void setStudents(Students students) {
		this.students = students;
	}

	@Column(name = "account_number")
	public Integer getAccountNumber() {
		return this.accountNumber;
	}

	public void setAccountNumber(Integer accountNumber) {
		this.accountNumber = accountNumber;
	}

	@Column(name = "other_account_details")
	public String getOtherAccountDetails() {
		return this.otherAccountDetails;
	}

	public void setOtherAccountDetails(String otherAccountDetails) {
		this.otherAccountDetails = otherAccountDetails;
	}

}
