package com.ifi.entity;
// Generated Sep 27, 2018 11:38:39 AM by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ActualPayments generated by hbm2java
 */
@Entity
@Table(name = "actual_payments", catalog = "student_loans")
public class ActualPayments implements java.io.Serializable {

	private Integer actualPaymentId;
	private Students students;
	private Date actualPaymentDate;
	private String actualPaymentAmount;
	private String actualPaymentDetails;

	public ActualPayments() {
	}

	public ActualPayments(Students students, Date actualPaymentDate, String actualPaymentAmount,
			String actualPaymentDetails) {
		this.students = students;
		this.actualPaymentDate = actualPaymentDate;
		this.actualPaymentAmount = actualPaymentAmount;
		this.actualPaymentDetails = actualPaymentDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "actual_payment_id", unique = true, nullable = false)
	public Integer getActualPaymentId() {
		return this.actualPaymentId;
	}

	public void setActualPaymentId(Integer actualPaymentId) {
		this.actualPaymentId = actualPaymentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "student_id")
	public Students getStudents() {
		return this.students;
	}

	public void setStudents(Students students) {
		this.students = students;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "actual_payment_date", length = 19)
	public Date getActualPaymentDate() {
		return this.actualPaymentDate;
	}

	public void setActualPaymentDate(Date actualPaymentDate) {
		this.actualPaymentDate = actualPaymentDate;
	}

	@Column(name = "actual_payment_amount")
	public String getActualPaymentAmount() {
		return this.actualPaymentAmount;
	}

	public void setActualPaymentAmount(String actualPaymentAmount) {
		this.actualPaymentAmount = actualPaymentAmount;
	}

	@Column(name = "actual_payment_details")
	public String getActualPaymentDetails() {
		return this.actualPaymentDetails;
	}

	public void setActualPaymentDetails(String actualPaymentDetails) {
		this.actualPaymentDetails = actualPaymentDetails;
	}

}
