package com.ifi.entity;
// Generated Sep 27, 2018 11:38:39 AM by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Addresses generated by hbm2java
 */
@Entity
@Table(name = "addresses", catalog = "student_loans")
public class Addresses implements java.io.Serializable {

	private Integer addressId;
	private String line1;
	private String line2;
	private String line3;
	private String line4;
	private String city;
	private String zipPostcode;
	private String stateProvinceCounty;
	private String country;
	private String otherAddressDetails;
	private Set<Guarantors> guarantorses = new HashSet<Guarantors>(0);
	private Set<StudentAddresses> studentAddresseses = new HashSet<StudentAddresses>(0);

	public Addresses() {
	}

	public Addresses(String line1, String line2, String line3, String line4, String city, String zipPostcode,
			String stateProvinceCounty, String country, String otherAddressDetails, Set<Guarantors> guarantorses,
			Set<StudentAddresses> studentAddresseses) {
		this.line1 = line1;
		this.line2 = line2;
		this.line3 = line3;
		this.line4 = line4;
		this.city = city;
		this.zipPostcode = zipPostcode;
		this.stateProvinceCounty = stateProvinceCounty;
		this.country = country;
		this.otherAddressDetails = otherAddressDetails;
		this.guarantorses = guarantorses;
		this.studentAddresseses = studentAddresseses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "address_id", unique = true, nullable = false)
	public Integer getAddressId() {
		return this.addressId;
	}

	public void setAddressId(Integer addressId) {
		this.addressId = addressId;
	}

	@Column(name = "line_1")
	public String getLine1() {
		return this.line1;
	}

	public void setLine1(String line1) {
		this.line1 = line1;
	}

	@Column(name = "line_2")
	public String getLine2() {
		return this.line2;
	}

	public void setLine2(String line2) {
		this.line2 = line2;
	}

	@Column(name = "line_3")
	public String getLine3() {
		return this.line3;
	}

	public void setLine3(String line3) {
		this.line3 = line3;
	}

	@Column(name = "line_4")
	public String getLine4() {
		return this.line4;
	}

	public void setLine4(String line4) {
		this.line4 = line4;
	}

	@Column(name = "city")
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "zip_postcode")
	public String getZipPostcode() {
		return this.zipPostcode;
	}

	public void setZipPostcode(String zipPostcode) {
		this.zipPostcode = zipPostcode;
	}

	@Column(name = "state_province_county")
	public String getStateProvinceCounty() {
		return this.stateProvinceCounty;
	}

	public void setStateProvinceCounty(String stateProvinceCounty) {
		this.stateProvinceCounty = stateProvinceCounty;
	}

	@Column(name = "country")
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "other_address_details")
	public String getOtherAddressDetails() {
		return this.otherAddressDetails;
	}

	public void setOtherAddressDetails(String otherAddressDetails) {
		this.otherAddressDetails = otherAddressDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "addresses")
	public Set<Guarantors> getGuarantorses() {
		return this.guarantorses;
	}

	public void setGuarantorses(Set<Guarantors> guarantorses) {
		this.guarantorses = guarantorses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "addresses")
	public Set<StudentAddresses> getStudentAddresseses() {
		return this.studentAddresseses;
	}

	public void setStudentAddresseses(Set<StudentAddresses> studentAddresseses) {
		this.studentAddresseses = studentAddresseses;
	}

}
