package com.ifi.entity;
// Generated Sep 27, 2018 11:38:39 AM by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RefAccountTypes generated by hbm2java
 */
@Entity
@Table(name = "ref_account_types", catalog = "student_loans")
public class RefAccountTypes implements java.io.Serializable {

	private Integer accountTypeCode;
	private String accountTypeDescription;
	private Set<Accounts> accountses = new HashSet<Accounts>(0);

	public RefAccountTypes() {
	}

	public RefAccountTypes(String accountTypeDescription, Set<Accounts> accountses) {
		this.accountTypeDescription = accountTypeDescription;
		this.accountses = accountses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "account_type_code", unique = true, nullable = false)
	public Integer getAccountTypeCode() {
		return this.accountTypeCode;
	}

	public void setAccountTypeCode(Integer accountTypeCode) {
		this.accountTypeCode = accountTypeCode;
	}

	@Column(name = "account_type_description")
	public String getAccountTypeDescription() {
		return this.accountTypeDescription;
	}

	public void setAccountTypeDescription(String accountTypeDescription) {
		this.accountTypeDescription = accountTypeDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refAccountTypes")
	public Set<Accounts> getAccountses() {
		return this.accountses;
	}

	public void setAccountses(Set<Accounts> accountses) {
		this.accountses = accountses;
	}

}
