package com.ifi.entity;
// Generated Sep 27, 2018 11:38:39 AM by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RefAddressTypes generated by hbm2java
 */
@Entity
@Table(name = "ref_address_types", catalog = "student_loans")
public class RefAddressTypes implements java.io.Serializable {

	private Integer addressTypeCode;
	private String addressTypeDescription;
	private Set<StudentAddresses> studentAddresseses = new HashSet<StudentAddresses>(0);

	public RefAddressTypes() {
	}

	public RefAddressTypes(String addressTypeDescription, Set<StudentAddresses> studentAddresseses) {
		this.addressTypeDescription = addressTypeDescription;
		this.studentAddresseses = studentAddresseses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "address_type_code", unique = true, nullable = false)
	public Integer getAddressTypeCode() {
		return this.addressTypeCode;
	}

	public void setAddressTypeCode(Integer addressTypeCode) {
		this.addressTypeCode = addressTypeCode;
	}

	@Column(name = "address_type_description")
	public String getAddressTypeDescription() {
		return this.addressTypeDescription;
	}

	public void setAddressTypeDescription(String addressTypeDescription) {
		this.addressTypeDescription = addressTypeDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refAddressTypes")
	public Set<StudentAddresses> getStudentAddresseses() {
		return this.studentAddresseses;
	}

	public void setStudentAddresseses(Set<StudentAddresses> studentAddresseses) {
		this.studentAddresseses = studentAddresseses;
	}

}
