package com.ifi.entity;
// Generated Sep 27, 2018 11:38:39 AM by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RefPaymentStatus generated by hbm2java
 */
@Entity
@Table(name = "ref_payment_status", catalog = "student_loans")
public class RefPaymentStatus implements java.io.Serializable {

	private Integer paymentStatusCode;
	private String paymentStatusDescription;
	private Set<PlannedPayments> plannedPaymentses = new HashSet<PlannedPayments>(0);

	public RefPaymentStatus() {
	}

	public RefPaymentStatus(String paymentStatusDescription, Set<PlannedPayments> plannedPaymentses) {
		this.paymentStatusDescription = paymentStatusDescription;
		this.plannedPaymentses = plannedPaymentses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "payment_status_code", unique = true, nullable = false)
	public Integer getPaymentStatusCode() {
		return this.paymentStatusCode;
	}

	public void setPaymentStatusCode(Integer paymentStatusCode) {
		this.paymentStatusCode = paymentStatusCode;
	}

	@Column(name = "payment_status_description")
	public String getPaymentStatusDescription() {
		return this.paymentStatusDescription;
	}

	public void setPaymentStatusDescription(String paymentStatusDescription) {
		this.paymentStatusDescription = paymentStatusDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refPaymentStatus")
	public Set<PlannedPayments> getPlannedPaymentses() {
		return this.plannedPaymentses;
	}

	public void setPlannedPaymentses(Set<PlannedPayments> plannedPaymentses) {
		this.plannedPaymentses = plannedPaymentses;
	}

}
