package com.ifi.entity;
// Generated Sep 27, 2018 11:38:39 AM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * StandardLoans generated by hbm2java
 */
@Entity
@Table(name = "standard_loans", catalog = "student_loans")
public class StandardLoans implements java.io.Serializable {

	private Integer standardLoanId;
	private String standardLoanName;
	private String standardLoanMinAmount;
	private String standardLoanMaxAmount;
	private String standardLoanPeriod;
	private String standardLoanDescription;
	private String standardLoanDetails;
	private StudentLoans studentLoans;

	public StandardLoans() {
	}

	public StandardLoans(String standardLoanName, String standardLoanMinAmount, String standardLoanMaxAmount,
			String standardLoanPeriod, String standardLoanDescription, String standardLoanDetails,
			StudentLoans studentLoans) {
		this.standardLoanName = standardLoanName;
		this.standardLoanMinAmount = standardLoanMinAmount;
		this.standardLoanMaxAmount = standardLoanMaxAmount;
		this.standardLoanPeriod = standardLoanPeriod;
		this.standardLoanDescription = standardLoanDescription;
		this.standardLoanDetails = standardLoanDetails;
		this.studentLoans = studentLoans;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "standard_loan_id", unique = true, nullable = false)
	public Integer getStandardLoanId() {
		return this.standardLoanId;
	}

	public void setStandardLoanId(Integer standardLoanId) {
		this.standardLoanId = standardLoanId;
	}

	@Column(name = "standard_loan_name")
	public String getStandardLoanName() {
		return this.standardLoanName;
	}

	public void setStandardLoanName(String standardLoanName) {
		this.standardLoanName = standardLoanName;
	}

	@Column(name = "standard_loan_min_amount")
	public String getStandardLoanMinAmount() {
		return this.standardLoanMinAmount;
	}

	public void setStandardLoanMinAmount(String standardLoanMinAmount) {
		this.standardLoanMinAmount = standardLoanMinAmount;
	}

	@Column(name = "standard_loan_max_amount")
	public String getStandardLoanMaxAmount() {
		return this.standardLoanMaxAmount;
	}

	public void setStandardLoanMaxAmount(String standardLoanMaxAmount) {
		this.standardLoanMaxAmount = standardLoanMaxAmount;
	}

	@Column(name = "standard_loan_period")
	public String getStandardLoanPeriod() {
		return this.standardLoanPeriod;
	}

	public void setStandardLoanPeriod(String standardLoanPeriod) {
		this.standardLoanPeriod = standardLoanPeriod;
	}

	@Column(name = "standard_loan_description")
	public String getStandardLoanDescription() {
		return this.standardLoanDescription;
	}

	public void setStandardLoanDescription(String standardLoanDescription) {
		this.standardLoanDescription = standardLoanDescription;
	}

	@Column(name = "standard_loan_details")
	public String getStandardLoanDetails() {
		return this.standardLoanDetails;
	}

	public void setStandardLoanDetails(String standardLoanDetails) {
		this.standardLoanDetails = standardLoanDetails;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "standardLoans")
	public StudentLoans getStudentLoans() {
		return this.studentLoans;
	}

	public void setStudentLoans(StudentLoans studentLoans) {
		this.studentLoans = studentLoans;
	}

}
