package com.ifi.entity;
// Generated Sep 27, 2018 11:38:39 AM by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * StudentLoans generated by hbm2java
 */
@Entity
@Table(name = "student_loans", catalog = "student_loans")
public class StudentLoans implements java.io.Serializable {

	private Integer studentLoanId;
	private Guarantors guarantors;
	private RefLoanStatus refLoanStatus;
	private StandardLoans standardLoans;
	private Students students;
	private Integer standardLoanId;
	private String studentLoanAmount;
	private String studentLoanPeriod;
	private Date fistRepaymentDate;
	private Date lastPaymentDate;
	private String studentLoanComments;
	private String studentLoanDetails;

	public StudentLoans() {
	}

	public StudentLoans(StandardLoans standardLoans) {
		this.standardLoans = standardLoans;
	}

	public StudentLoans(Guarantors guarantors, RefLoanStatus refLoanStatus, StandardLoans standardLoans,
			Students students, Integer standardLoanId, String studentLoanAmount, String studentLoanPeriod,
			Date fistRepaymentDate, Date lastPaymentDate, String studentLoanComments, String studentLoanDetails) {
		this.guarantors = guarantors;
		this.refLoanStatus = refLoanStatus;
		this.standardLoans = standardLoans;
		this.students = students;
		this.standardLoanId = standardLoanId;
		this.studentLoanAmount = studentLoanAmount;
		this.studentLoanPeriod = studentLoanPeriod;
		this.fistRepaymentDate = fistRepaymentDate;
		this.lastPaymentDate = lastPaymentDate;
		this.studentLoanComments = studentLoanComments;
		this.studentLoanDetails = studentLoanDetails;
	}

	@GenericGenerator(name = "com.ifi.entity.StudentLoansIdGenerator", strategy = "foreign", parameters = @Parameter(name = "property", value = "standardLoans"))
	@Id
	@GeneratedValue(generator = "com.ifi.entity.StudentLoansIdGenerator")

	@Column(name = "student_loan_id", unique = true, nullable = false)
	public Integer getStudentLoanId() {
		return this.studentLoanId;
	}

	public void setStudentLoanId(Integer studentLoanId) {
		this.studentLoanId = studentLoanId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "guarator_id")
	public Guarantors getGuarantors() {
		return this.guarantors;
	}

	public void setGuarantors(Guarantors guarantors) {
		this.guarantors = guarantors;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "loan_status_code")
	public RefLoanStatus getRefLoanStatus() {
		return this.refLoanStatus;
	}

	public void setRefLoanStatus(RefLoanStatus refLoanStatus) {
		this.refLoanStatus = refLoanStatus;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public StandardLoans getStandardLoans() {
		return this.standardLoans;
	}

	public void setStandardLoans(StandardLoans standardLoans) {
		this.standardLoans = standardLoans;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "student_id")
	public Students getStudents() {
		return this.students;
	}

	public void setStudents(Students students) {
		this.students = students;
	}

	@Column(name = "standard_loan_id")
	public Integer getStandardLoanId() {
		return this.standardLoanId;
	}

	public void setStandardLoanId(Integer standardLoanId) {
		this.standardLoanId = standardLoanId;
	}

	@Column(name = "student_loan_amount")
	public String getStudentLoanAmount() {
		return this.studentLoanAmount;
	}

	public void setStudentLoanAmount(String studentLoanAmount) {
		this.studentLoanAmount = studentLoanAmount;
	}

	@Column(name = "student_loan_period")
	public String getStudentLoanPeriod() {
		return this.studentLoanPeriod;
	}

	public void setStudentLoanPeriod(String studentLoanPeriod) {
		this.studentLoanPeriod = studentLoanPeriod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fist_repayment_date", length = 19)
	public Date getFistRepaymentDate() {
		return this.fistRepaymentDate;
	}

	public void setFistRepaymentDate(Date fistRepaymentDate) {
		this.fistRepaymentDate = fistRepaymentDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_payment_date", length = 19)
	public Date getLastPaymentDate() {
		return this.lastPaymentDate;
	}

	public void setLastPaymentDate(Date lastPaymentDate) {
		this.lastPaymentDate = lastPaymentDate;
	}

	@Column(name = "student_loan_comments")
	public String getStudentLoanComments() {
		return this.studentLoanComments;
	}

	public void setStudentLoanComments(String studentLoanComments) {
		this.studentLoanComments = studentLoanComments;
	}

	@Column(name = "student_loan_details")
	public String getStudentLoanDetails() {
		return this.studentLoanDetails;
	}

	public void setStudentLoanDetails(String studentLoanDetails) {
		this.studentLoanDetails = studentLoanDetails;
	}

}
