package com.ifi.entity;
// Generated Sep 27, 2018 10:28:46 AM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Airports generated by hbm2java
 */
@Entity
@Table(name = "airports", catalog = "flight_booking")
public class Airports implements java.io.Serializable {

	private Integer airportCode;
	private String airportName;
	private String airportLocation;
	private String otherDetails;
	private Set<Legs> legses = new HashSet<Legs>(0);
	private Set<FlightSchedules> flightScheduleses = new HashSet<FlightSchedules>(0);

	public Airports() {
	}

	public Airports(String airportName, String airportLocation, String otherDetails, Set<Legs> legses,
			Set<FlightSchedules> flightScheduleses) {
		this.airportName = airportName;
		this.airportLocation = airportLocation;
		this.otherDetails = otherDetails;
		this.legses = legses;
		this.flightScheduleses = flightScheduleses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "airport_code", unique = true, nullable = false)
	public Integer getAirportCode() {
		return this.airportCode;
	}

	public void setAirportCode(Integer airportCode) {
		this.airportCode = airportCode;
	}

	@Column(name = "airport_name")
	public String getAirportName() {
		return this.airportName;
	}

	public void setAirportName(String airportName) {
		this.airportName = airportName;
	}

	@Column(name = "airport_location")
	public String getAirportLocation() {
		return this.airportLocation;
	}

	public void setAirportLocation(String airportLocation) {
		this.airportLocation = airportLocation;
	}

	@Column(name = "other_details")
	public String getOtherDetails() {
		return this.otherDetails;
	}

	public void setOtherDetails(String otherDetails) {
		this.otherDetails = otherDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "airports")
	public Set<Legs> getLegses() {
		return this.legses;
	}

	public void setLegses(Set<Legs> legses) {
		this.legses = legses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "airports")
	public Set<FlightSchedules> getFlightScheduleses() {
		return this.flightScheduleses;
	}

	public void setFlightScheduleses(Set<FlightSchedules> flightScheduleses) {
		this.flightScheduleses = flightScheduleses;
	}

}
