package com.ifi.entity;
// Generated Sep 27, 2018 10:28:46 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FlightSchedules generated by hbm2java
 */
@Entity
@Table(name = "flight_schedules", catalog = "flight_booking")
public class FlightSchedules implements java.io.Serializable {

	private Integer flightNumber;
	private Airports airports;
	private Integer usualAircraftTypeCode;
	private Integer originAirportCode;
	private Integer destinationAirportCode;
	private Date departureDateTime;
	private Date arrivalDateTime;
	private FlightCosts flightCosts;
	private Set<Legs> legses = new HashSet<Legs>(0);

	public FlightSchedules() {
	}

	public FlightSchedules(Airports airports, Integer usualAircraftTypeCode, Integer originAirportCode,
			Integer destinationAirportCode, Date departureDateTime, Date arrivalDateTime, FlightCosts flightCosts,
			Set<Legs> legses) {
		this.airports = airports;
		this.usualAircraftTypeCode = usualAircraftTypeCode;
		this.originAirportCode = originAirportCode;
		this.destinationAirportCode = destinationAirportCode;
		this.departureDateTime = departureDateTime;
		this.arrivalDateTime = arrivalDateTime;
		this.flightCosts = flightCosts;
		this.legses = legses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "flight_number", unique = true, nullable = false)
	public Integer getFlightNumber() {
		return this.flightNumber;
	}

	public void setFlightNumber(Integer flightNumber) {
		this.flightNumber = flightNumber;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "airline_code")
	public Airports getAirports() {
		return this.airports;
	}

	public void setAirports(Airports airports) {
		this.airports = airports;
	}

	@Column(name = "usual_aircraft_type_code")
	public Integer getUsualAircraftTypeCode() {
		return this.usualAircraftTypeCode;
	}

	public void setUsualAircraftTypeCode(Integer usualAircraftTypeCode) {
		this.usualAircraftTypeCode = usualAircraftTypeCode;
	}

	@Column(name = "origin_airport_code")
	public Integer getOriginAirportCode() {
		return this.originAirportCode;
	}

	public void setOriginAirportCode(Integer originAirportCode) {
		this.originAirportCode = originAirportCode;
	}

	@Column(name = "destination_airport_code")
	public Integer getDestinationAirportCode() {
		return this.destinationAirportCode;
	}

	public void setDestinationAirportCode(Integer destinationAirportCode) {
		this.destinationAirportCode = destinationAirportCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "departure_date_time", length = 19)
	public Date getDepartureDateTime() {
		return this.departureDateTime;
	}

	public void setDepartureDateTime(Date departureDateTime) {
		this.departureDateTime = departureDateTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "arrival_date_time", length = 19)
	public Date getArrivalDateTime() {
		return this.arrivalDateTime;
	}

	public void setArrivalDateTime(Date arrivalDateTime) {
		this.arrivalDateTime = arrivalDateTime;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "flightSchedules")
	public FlightCosts getFlightCosts() {
		return this.flightCosts;
	}

	public void setFlightCosts(FlightCosts flightCosts) {
		this.flightCosts = flightCosts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "flightSchedules")
	public Set<Legs> getLegses() {
		return this.legses;
	}

	public void setLegses(Set<Legs> legses) {
		this.legses = legses;
	}

}
