package com.ifi.entity;
// Generated Sep 27, 2018 10:28:46 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Legs generated by hbm2java
 */
@Entity
@Table(name = "legs", catalog = "flight_booking")
public class Legs implements java.io.Serializable {

	private Integer legId;
	private Airports airports;
	private FlightSchedules flightSchedules;
	private Integer destinationAirportCode;
	private Date actualDepartureTime;
	private Date actualArrivalTime;
	private Set<LtineraryReservations> ltineraryReservationses = new HashSet<LtineraryReservations>(0);

	public Legs() {
	}

	public Legs(Airports airports, FlightSchedules flightSchedules, Integer destinationAirportCode,
			Date actualDepartureTime, Date actualArrivalTime, Set<LtineraryReservations> ltineraryReservationses) {
		this.airports = airports;
		this.flightSchedules = flightSchedules;
		this.destinationAirportCode = destinationAirportCode;
		this.actualDepartureTime = actualDepartureTime;
		this.actualArrivalTime = actualArrivalTime;
		this.ltineraryReservationses = ltineraryReservationses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "leg_id", unique = true, nullable = false)
	public Integer getLegId() {
		return this.legId;
	}

	public void setLegId(Integer legId) {
		this.legId = legId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "origin_airport_code")
	public Airports getAirports() {
		return this.airports;
	}

	public void setAirports(Airports airports) {
		this.airports = airports;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "flight_number")
	public FlightSchedules getFlightSchedules() {
		return this.flightSchedules;
	}

	public void setFlightSchedules(FlightSchedules flightSchedules) {
		this.flightSchedules = flightSchedules;
	}

	@Column(name = "destination_airport_code")
	public Integer getDestinationAirportCode() {
		return this.destinationAirportCode;
	}

	public void setDestinationAirportCode(Integer destinationAirportCode) {
		this.destinationAirportCode = destinationAirportCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "actual_departure_time", length = 19)
	public Date getActualDepartureTime() {
		return this.actualDepartureTime;
	}

	public void setActualDepartureTime(Date actualDepartureTime) {
		this.actualDepartureTime = actualDepartureTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "actual_arrival_time", length = 19)
	public Date getActualArrivalTime() {
		return this.actualArrivalTime;
	}

	public void setActualArrivalTime(Date actualArrivalTime) {
		this.actualArrivalTime = actualArrivalTime;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "legses")
	public Set<LtineraryReservations> getLtineraryReservationses() {
		return this.ltineraryReservationses;
	}

	public void setLtineraryReservationses(Set<LtineraryReservations> ltineraryReservationses) {
		this.ltineraryReservationses = ltineraryReservationses;
	}

}
