package com.ifi.entity;
// Generated Sep 27, 2018 10:28:46 AM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Passengers generated by hbm2java
 */
@Entity
@Table(name = "passengers", catalog = "flight_booking")
public class Passengers implements java.io.Serializable {

	private Integer passengerId;
	private String firstName;
	private String secondName;
	private String lastName;
	private Integer phoneNumber;
	private String emailAddress;
	private String addressLines;
	private String city;
	private String statProvinceCountry;
	private String country;
	private String otherPassengerDetails;
	private Set<LtineraryReservations> ltineraryReservationses = new HashSet<LtineraryReservations>(0);

	public Passengers() {
	}

	public Passengers(String firstName, String secondName, String lastName, Integer phoneNumber, String emailAddress,
			String addressLines, String city, String statProvinceCountry, String country, String otherPassengerDetails,
			Set<LtineraryReservations> ltineraryReservationses) {
		this.firstName = firstName;
		this.secondName = secondName;
		this.lastName = lastName;
		this.phoneNumber = phoneNumber;
		this.emailAddress = emailAddress;
		this.addressLines = addressLines;
		this.city = city;
		this.statProvinceCountry = statProvinceCountry;
		this.country = country;
		this.otherPassengerDetails = otherPassengerDetails;
		this.ltineraryReservationses = ltineraryReservationses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "passenger_id", unique = true, nullable = false)
	public Integer getPassengerId() {
		return this.passengerId;
	}

	public void setPassengerId(Integer passengerId) {
		this.passengerId = passengerId;
	}

	@Column(name = "first_name")
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "second_name")
	public String getSecondName() {
		return this.secondName;
	}

	public void setSecondName(String secondName) {
		this.secondName = secondName;
	}

	@Column(name = "last_name")
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "phone_number")
	public Integer getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(Integer phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "email_address")
	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	@Column(name = "address_lines")
	public String getAddressLines() {
		return this.addressLines;
	}

	public void setAddressLines(String addressLines) {
		this.addressLines = addressLines;
	}

	@Column(name = "city")
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "stat_province_country")
	public String getStatProvinceCountry() {
		return this.statProvinceCountry;
	}

	public void setStatProvinceCountry(String statProvinceCountry) {
		this.statProvinceCountry = statProvinceCountry;
	}

	@Column(name = "country")
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "other_passenger_details")
	public String getOtherPassengerDetails() {
		return this.otherPassengerDetails;
	}

	public void setOtherPassengerDetails(String otherPassengerDetails) {
		this.otherPassengerDetails = otherPassengerDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "passengers")
	public Set<LtineraryReservations> getLtineraryReservationses() {
		return this.ltineraryReservationses;
	}

	public void setLtineraryReservationses(Set<LtineraryReservations> ltineraryReservationses) {
		this.ltineraryReservationses = ltineraryReservationses;
	}

}
