package com.ifi.entity;
// Generated Sep 27, 2018 10:28:46 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Payments generated by hbm2java
 */
@Entity
@Table(name = "payments", catalog = "flight_booking")
public class Payments implements java.io.Serializable {

	private Integer paymentId;
	private Integer paymentStatusCode;
	private Date paymentDate;
	private String paymentAmount;
	private Set<LtineraryReservations> ltineraryReservationses = new HashSet<LtineraryReservations>(0);

	public Payments() {
	}

	public Payments(Integer paymentStatusCode, Date paymentDate, String paymentAmount,
			Set<LtineraryReservations> ltineraryReservationses) {
		this.paymentStatusCode = paymentStatusCode;
		this.paymentDate = paymentDate;
		this.paymentAmount = paymentAmount;
		this.ltineraryReservationses = ltineraryReservationses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "payment_id", unique = true, nullable = false)
	public Integer getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(Integer paymentId) {
		this.paymentId = paymentId;
	}

	@Column(name = "payment_status_code")
	public Integer getPaymentStatusCode() {
		return this.paymentStatusCode;
	}

	public void setPaymentStatusCode(Integer paymentStatusCode) {
		this.paymentStatusCode = paymentStatusCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "payment_date", length = 19)
	public Date getPaymentDate() {
		return this.paymentDate;
	}

	public void setPaymentDate(Date paymentDate) {
		this.paymentDate = paymentDate;
	}

	@Column(name = "payment_amount")
	public String getPaymentAmount() {
		return this.paymentAmount;
	}

	public void setPaymentAmount(String paymentAmount) {
		this.paymentAmount = paymentAmount;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "paymentses")
	public Set<LtineraryReservations> getLtineraryReservationses() {
		return this.ltineraryReservationses;
	}

	public void setLtineraryReservationses(Set<LtineraryReservations> ltineraryReservationses) {
		this.ltineraryReservationses = ltineraryReservationses;
	}

}
