package com.ifi.entity;
// Generated Sep 27, 2018 10:28:46 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RefCalendar generated by hbm2java
 */
@Entity
@Table(name = "ref_calendar", catalog = "flight_booking")
public class RefCalendar implements java.io.Serializable {

	private Date dayDate;
	private Integer dayNumber;
	private String businessDayYn;
	private Set<FlightCosts> flightCostses = new HashSet<FlightCosts>(0);

	public RefCalendar() {
	}

	public RefCalendar(Date dayDate) {
		this.dayDate = dayDate;
	}

	public RefCalendar(Date dayDate, Integer dayNumber, String businessDayYn, Set<FlightCosts> flightCostses) {
		this.dayDate = dayDate;
		this.dayNumber = dayNumber;
		this.businessDayYn = businessDayYn;
		this.flightCostses = flightCostses;
	}

	@Id

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "day_date", unique = true, nullable = false, length = 19)
	public Date getDayDate() {
		return this.dayDate;
	}

	public void setDayDate(Date dayDate) {
		this.dayDate = dayDate;
	}

	@Column(name = "day_number")
	public Integer getDayNumber() {
		return this.dayNumber;
	}

	public void setDayNumber(Integer dayNumber) {
		this.dayNumber = dayNumber;
	}

	@Column(name = "business_day_yn")
	public String getBusinessDayYn() {
		return this.businessDayYn;
	}

	public void setBusinessDayYn(String businessDayYn) {
		this.businessDayYn = businessDayYn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refCalendar")
	public Set<FlightCosts> getFlightCostses() {
		return this.flightCostses;
	}

	public void setFlightCostses(Set<FlightCosts> flightCostses) {
		this.flightCostses = flightCostses;
	}

}
