/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 10:31:43 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.service;



import java.util.List;

import javax.transaction.Transactional;

import com.ifi.entity.Accounts;
import com.ifi.repository.AccountsRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class AccountsServiceImpl implements AccountsService {

	@Autowired
	private AccountsRepository accountsRepository;

	@Override
	public Accounts getOne(Integer accountId) {
		return accountsRepository.getOne(accountId);
	}

	@Override
	public Boolean delete(Integer accountId) {
		if (accountsRepository.getOne(accountId) != null) {
			accountsRepository.deleteById(accountId);
			return true;
		}
		return false;
	}

	@Override
	public Accounts create(Accounts accounts) {
		return accountsRepository.save(accounts);
	}

	@Override
	public Accounts update(Accounts accountsToUpdate) {
						Accounts accounts = accountsRepository.getOne(accountsToUpdate.getAccountId());
																										
				if(accountsToUpdate.getRefAccountTypes() !=null) {
			
		}
				if(accountsToUpdate.getRefBanks() !=null) {
			
		}
				if(accountsToUpdate.getStudents() !=null) {
			
		}
				if(accountsToUpdate.getAccountNumber() !=null) {
			
		}
				if(accountsToUpdate.getOtherAccountDetails() !=null) {
			
		}
				return accountsRepository.save(accounts);
	}

	@Override
	public Boolean exist(Accounts accounts) {
						return accountsRepository.existsById(accounts.getAccountId());
																									}

	@Override
	public List<Accounts> findAll() {
		return accountsRepository.findAll();
	}

}

