/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 10:31:43 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.service;

import com.ifi.entity.Accounts;
import java.util.List;

public interface AccountsService {

	public Accounts getOne(Integer accountId);

	public List<Accounts> findAll();

	public Boolean delete(Integer accountId);

	public Accounts create(Accounts accounts);

	public Accounts update(Accounts accounts);

	public Boolean exist(Accounts accounts);
}
