/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 10:31:43 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.service;



import java.util.List;

import javax.transaction.Transactional;

import com.ifi.entity.ActualPayments;
import com.ifi.repository.ActualPaymentsRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class ActualPaymentsServiceImpl implements ActualPaymentsService {

	@Autowired
	private ActualPaymentsRepository actualPaymentsRepository;

	@Override
	public ActualPayments getOne(Integer actualPaymentId) {
		return actualPaymentsRepository.getOne(actualPaymentId);
	}

	@Override
	public Boolean delete(Integer actualPaymentId) {
		if (actualPaymentsRepository.getOne(actualPaymentId) != null) {
			actualPaymentsRepository.deleteById(actualPaymentId);
			return true;
		}
		return false;
	}

	@Override
	public ActualPayments create(ActualPayments actualPayments) {
		return actualPaymentsRepository.save(actualPayments);
	}

	@Override
	public ActualPayments update(ActualPayments actualPaymentsToUpdate) {
						ActualPayments actualPayments = actualPaymentsRepository.getOne(actualPaymentsToUpdate.getActualPaymentId());
																						
				if(actualPaymentsToUpdate.getStudents() !=null) {
			
		}
				if(actualPaymentsToUpdate.getActualPaymentDate() !=null) {
			
		}
				if(actualPaymentsToUpdate.getActualPaymentAmount() !=null) {
			
		}
				if(actualPaymentsToUpdate.getActualPaymentDetails() !=null) {
			
		}
				return actualPaymentsRepository.save(actualPayments);
	}

	@Override
	public Boolean exist(ActualPayments actualPayments) {
						return actualPaymentsRepository.existsById(actualPayments.getActualPaymentId());
																					}

	@Override
	public List<ActualPayments> findAll() {
		return actualPaymentsRepository.findAll();
	}

}

