/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 11:44:53 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.service;

import com.ifi.entity.Addresses;
import java.util.List;

public interface AddressesService {

	public Addresses getOne(Integer addressId);

	public List<Addresses> findAll();

	public Boolean delete(Integer addressId);

	public Addresses create(Addresses addresses);

	public Addresses update(Addresses addresses);

	public Boolean exist(Addresses addresses);
}
