/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 10:31:43 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.service;

import com.ifi.entity.Guarantors;
import java.util.List;

public interface GuarantorsService {

	public Guarantors getOne(Integer guarantorId);

	public List<Guarantors> findAll();

	public Boolean delete(Integer guarantorId);

	public Guarantors create(Guarantors guarantors);

	public Guarantors update(Guarantors guarantors);

	public Boolean exist(Guarantors guarantors);
}
