/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 10:31:43 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.service;



import java.util.List;

import javax.transaction.Transactional;

import com.ifi.entity.Guarantors;
import com.ifi.repository.GuarantorsRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class GuarantorsServiceImpl implements GuarantorsService {

	@Autowired
	private GuarantorsRepository guarantorsRepository;

	@Override
	public Guarantors getOne(Integer guarantorId) {
		return guarantorsRepository.getOne(guarantorId);
	}

	@Override
	public Boolean delete(Integer guarantorId) {
		if (guarantorsRepository.getOne(guarantorId) != null) {
			guarantorsRepository.deleteById(guarantorId);
			return true;
		}
		return false;
	}

	@Override
	public Guarantors create(Guarantors guarantors) {
		return guarantorsRepository.save(guarantors);
	}

	@Override
	public Guarantors update(Guarantors guarantorsToUpdate) {
						Guarantors guarantors = guarantorsRepository.getOne(guarantorsToUpdate.getGuarantorId());
																										
				if(guarantorsToUpdate.getAddresses() !=null) {
			
		}
				if(guarantorsToUpdate.getGuarantorName() !=null) {
			
		}
				if(guarantorsToUpdate.getGuarantorEmail() !=null) {
			
		}
				if(guarantorsToUpdate.getGuarantorPhone() !=null) {
			
		}
				if(guarantorsToUpdate.getOtherGuarantorDetails() !=null) {
			
		}
				return guarantorsRepository.save(guarantors);
	}

	@Override
	public Boolean exist(Guarantors guarantors) {
						return guarantorsRepository.existsById(guarantors.getGuarantorId());
																									}

	@Override
	public List<Guarantors> findAll() {
		return guarantorsRepository.findAll();
	}

}

