/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 10:31:43 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.service;

import com.ifi.entity.PlannedPayments;
import java.util.List;

public interface PlannedPaymentsService {

	public PlannedPayments getOne(Integer regularOrderId);

	public List<PlannedPayments> findAll();

	public Boolean delete(Integer regularOrderId);

	public PlannedPayments create(PlannedPayments plannedPayments);

	public PlannedPayments update(PlannedPayments plannedPayments);

	public Boolean exist(PlannedPayments plannedPayments);
}
