/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 10:31:43 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.service;

import com.ifi.entity.RefAccountTypes;
import java.util.List;

public interface RefAccountTypesService {

	public RefAccountTypes getOne(Integer accountTypeCode);

	public List<RefAccountTypes> findAll();

	public Boolean delete(Integer accountTypeCode);

	public RefAccountTypes create(RefAccountTypes refAccountTypes);

	public RefAccountTypes update(RefAccountTypes refAccountTypes);

	public Boolean exist(RefAccountTypes refAccountTypes);
}
