/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 10:31:43 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.service;

import com.ifi.entity.RefAddressTypes;
import java.util.List;

public interface RefAddressTypesService {

	public RefAddressTypes getOne(Integer addressTypeCode);

	public List<RefAddressTypes> findAll();

	public Boolean delete(Integer addressTypeCode);

	public RefAddressTypes create(RefAddressTypes refAddressTypes);

	public RefAddressTypes update(RefAddressTypes refAddressTypes);

	public Boolean exist(RefAddressTypes refAddressTypes);
}
