/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 10:31:43 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.service;



import java.util.List;

import javax.transaction.Transactional;

import com.ifi.entity.RefAccountTypes;
import com.ifi.repository.RefAccountTypesRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class RefAccountTypesServiceImpl implements RefAccountTypesService {

	@Autowired
	private RefAccountTypesRepository refAccountTypesRepository;

	@Override
	public RefAccountTypes getOne(Integer accountTypeCode) {
		return refAccountTypesRepository.getOne(accountTypeCode);
	}

	@Override
	public Boolean delete(Integer accountTypeCode) {
		if (refAccountTypesRepository.getOne(accountTypeCode) != null) {
			refAccountTypesRepository.deleteById(accountTypeCode);
			return true;
		}
		return false;
	}

	@Override
	public RefAccountTypes create(RefAccountTypes refAccountTypes) {
		return refAccountTypesRepository.save(refAccountTypes);
	}

	@Override
	public RefAccountTypes update(RefAccountTypes refAccountTypesToUpdate) {
						RefAccountTypes refAccountTypes = refAccountTypesRepository.getOne(refAccountTypesToUpdate.getAccountTypeCode());
										
				if(refAccountTypesToUpdate.getAccountTypeDescription() !=null) {
			
		}
				return refAccountTypesRepository.save(refAccountTypes);
	}

	@Override
	public Boolean exist(RefAccountTypes refAccountTypes) {
						return refAccountTypesRepository.existsById(refAccountTypes.getAccountTypeCode());
									}

	@Override
	public List<RefAccountTypes> findAll() {
		return refAccountTypesRepository.findAll();
	}

}

