/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 10:31:43 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.service;



import java.util.List;

import javax.transaction.Transactional;

import com.ifi.entity.RefBanks;
import com.ifi.repository.RefBanksRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class RefBanksServiceImpl implements RefBanksService {

	@Autowired
	private RefBanksRepository refBanksRepository;

	@Override
	public RefBanks getOne(Integer bankCode) {
		return refBanksRepository.getOne(bankCode);
	}

	@Override
	public Boolean delete(Integer bankCode) {
		if (refBanksRepository.getOne(bankCode) != null) {
			refBanksRepository.deleteById(bankCode);
			return true;
		}
		return false;
	}

	@Override
	public RefBanks create(RefBanks refBanks) {
		return refBanksRepository.save(refBanks);
	}

	@Override
	public RefBanks update(RefBanks refBanksToUpdate) {
						RefBanks refBanks = refBanksRepository.getOne(refBanksToUpdate.getBankCode());
										
				if(refBanksToUpdate.getBankName() !=null) {
			
		}
				return refBanksRepository.save(refBanks);
	}

	@Override
	public Boolean exist(RefBanks refBanks) {
						return refBanksRepository.existsById(refBanks.getBankCode());
									}

	@Override
	public List<RefBanks> findAll() {
		return refBanksRepository.findAll();
	}

}

