/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 10:31:43 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.service;



import java.util.List;

import javax.transaction.Transactional;

import com.ifi.entity.RefLoanStatus;
import com.ifi.repository.RefLoanStatusRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class RefLoanStatusServiceImpl implements RefLoanStatusService {

	@Autowired
	private RefLoanStatusRepository refLoanStatusRepository;

	@Override
	public RefLoanStatus getOne(Integer loanStatusCode) {
		return refLoanStatusRepository.getOne(loanStatusCode);
	}

	@Override
	public Boolean delete(Integer loanStatusCode) {
		if (refLoanStatusRepository.getOne(loanStatusCode) != null) {
			refLoanStatusRepository.deleteById(loanStatusCode);
			return true;
		}
		return false;
	}

	@Override
	public RefLoanStatus create(RefLoanStatus refLoanStatus) {
		return refLoanStatusRepository.save(refLoanStatus);
	}

	@Override
	public RefLoanStatus update(RefLoanStatus refLoanStatusToUpdate) {
						RefLoanStatus refLoanStatus = refLoanStatusRepository.getOne(refLoanStatusToUpdate.getLoanStatusCode());
										
				if(refLoanStatusToUpdate.getLoanStatusDescription() !=null) {
			
		}
				return refLoanStatusRepository.save(refLoanStatus);
	}

	@Override
	public Boolean exist(RefLoanStatus refLoanStatus) {
						return refLoanStatusRepository.existsById(refLoanStatus.getLoanStatusCode());
									}

	@Override
	public List<RefLoanStatus> findAll() {
		return refLoanStatusRepository.findAll();
	}

}

