/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 10:31:43 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.service;

import com.ifi.entity.RefLoanStatus;
import java.util.List;

public interface RefLoanStatusService {

	public RefLoanStatus getOne(Integer loanStatusCode);

	public List<RefLoanStatus> findAll();

	public Boolean delete(Integer loanStatusCode);

	public RefLoanStatus create(RefLoanStatus refLoanStatus);

	public RefLoanStatus update(RefLoanStatus refLoanStatus);

	public Boolean exist(RefLoanStatus refLoanStatus);
}
