/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 10:31:43 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.service;



import java.util.List;

import javax.transaction.Transactional;

import com.ifi.entity.RefPaymentStatus;
import com.ifi.repository.RefPaymentStatusRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class RefPaymentStatusServiceImpl implements RefPaymentStatusService {

	@Autowired
	private RefPaymentStatusRepository refPaymentStatusRepository;

	@Override
	public RefPaymentStatus getOne(Integer paymentStatusCode) {
		return refPaymentStatusRepository.getOne(paymentStatusCode);
	}

	@Override
	public Boolean delete(Integer paymentStatusCode) {
		if (refPaymentStatusRepository.getOne(paymentStatusCode) != null) {
			refPaymentStatusRepository.deleteById(paymentStatusCode);
			return true;
		}
		return false;
	}

	@Override
	public RefPaymentStatus create(RefPaymentStatus refPaymentStatus) {
		return refPaymentStatusRepository.save(refPaymentStatus);
	}

	@Override
	public RefPaymentStatus update(RefPaymentStatus refPaymentStatusToUpdate) {
						RefPaymentStatus refPaymentStatus = refPaymentStatusRepository.getOne(refPaymentStatusToUpdate.getPaymentStatusCode());
										
				if(refPaymentStatusToUpdate.getPaymentStatusDescription() !=null) {
			
		}
				return refPaymentStatusRepository.save(refPaymentStatus);
	}

	@Override
	public Boolean exist(RefPaymentStatus refPaymentStatus) {
						return refPaymentStatusRepository.existsById(refPaymentStatus.getPaymentStatusCode());
									}

	@Override
	public List<RefPaymentStatus> findAll() {
		return refPaymentStatusRepository.findAll();
	}

}

