/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 10:31:43 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.service;

import com.ifi.entity.RefPaymentStatus;
import java.util.List;

public interface RefPaymentStatusService {

	public RefPaymentStatus getOne(Integer paymentStatusCode);

	public List<RefPaymentStatus> findAll();

	public Boolean delete(Integer paymentStatusCode);

	public RefPaymentStatus create(RefPaymentStatus refPaymentStatus);

	public RefPaymentStatus update(RefPaymentStatus refPaymentStatus);

	public Boolean exist(RefPaymentStatus refPaymentStatus);
}
