/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 10:31:44 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.service;



import java.util.List;

import javax.transaction.Transactional;

import com.ifi.entity.Students;
import com.ifi.repository.StudentsRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class StudentsServiceImpl implements StudentsService {

	@Autowired
	private StudentsRepository studentsRepository;

	@Override
	public Students getOne(Integer studentId) {
		return studentsRepository.getOne(studentId);
	}

	@Override
	public Boolean delete(Integer studentId) {
		if (studentsRepository.getOne(studentId) != null) {
			studentsRepository.deleteById(studentId);
			return true;
		}
		return false;
	}

	@Override
	public Students create(Students students) {
		return studentsRepository.save(students);
	}

	@Override
	public Students update(Students studentsToUpdate) {
						Students students = studentsRepository.getOne(studentsToUpdate.getStudentId());
																						
				if(studentsToUpdate.getStudentName() !=null) {
			
		}
				if(studentsToUpdate.getStudentPhone() !=null) {
			
		}
				if(studentsToUpdate.getStudentEmail() !=null) {
			
		}
				if(studentsToUpdate.getOtherStudentDetails() !=null) {
			
		}
				return studentsRepository.save(students);
	}

	@Override
	public Boolean exist(Students students) {
						return studentsRepository.existsById(students.getStudentId());
																					}

	@Override
	public List<Students> findAll() {
		return studentsRepository.findAll();
	}

}

