/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 10:31:43 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.service;


import java.util.List;

import javax.transaction.Transactional;

import com.ifi.entity.StudentAddresses;
import com.ifi.repository.StudentAddressesRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class StudentAddressesServiceImpl implements StudentAddressesService {

	@Autowired
	private StudentAddressesRepository studentAddressesRepository;

	@Override
	public StudentAddresses getOne(Integer studentId) {
		return studentAddressesRepository.getOne(studentId);
	}

	@Override
	public Boolean delete(Integer studentId) {
		if (studentAddressesRepository.getOne(studentId) != null) {
			studentAddressesRepository.deleteById(studentId);
			return true;
		}
		return false;
	}

	@Override
	public StudentAddresses create(StudentAddresses studentAddresses) {
		return studentAddressesRepository.save(studentAddresses);
	}

	@Override
	public StudentAddresses update(StudentAddresses studentAddressesToUpdate) {
						StudentAddresses studentAddresses = studentAddressesRepository.getOne(studentAddressesToUpdate.getStudentId());
																						
				if(studentAddressesToUpdate.getAddresses() !=null) {
			
		}
				if(studentAddressesToUpdate.getDateFrom() !=null) {
			
		}
				if(studentAddressesToUpdate.getRefAddressTypes() !=null) {
			
		}
				if(studentAddressesToUpdate.getDateTo() !=null) {
			
		}
				return studentAddressesRepository.save(studentAddresses);
	}

	@Override
	public Boolean exist(StudentAddresses studentAddresses) {
						return studentAddressesRepository.existsById(studentAddresses.getStudentId());
																					}

	@Override
	public List<StudentAddresses> findAll() {
		return studentAddressesRepository.findAll();
	}

}

