/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 10:31:44 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.service;

import com.ifi.entity.Students;
import java.util.List;

public interface StudentsService {

	public Students getOne(Integer studentId);

	public List<Students> findAll();

	public Boolean delete(Integer studentId);

	public Students create(Students students);

	public Students update(Students students);

	public Boolean exist(Students students);
}
